In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

from multimodal_lancedb import MusicDatabase
from utils import (
    EmbeddingProcessor,
    Ranker,
    MusicSearchSystem
)
from IPython.display import Audio, display
import pandas as pd

In [2]:
# Initialize the system
search_system = MusicSearchSystem(db_path="./.lancedb_2", music_dir="music")

In [3]:
search_system.import_text_descriptions("final_dataset.csv", process_audio=True)

Successfully imported 200 records from final_dataset.csv
Processed audio for: My Rhapsody Sounds - Short Version A
Processed audio for: Laid Back - Short Version A
Processed audio for: Far Taj
Processed audio for: The Stones - Short Version
Processed audio for: Fixed - Short Version B
Processed audio for: Inside the War
Processed audio for: Locked in Silence - Short Version C
Processed audio for: How Could I Know - Intro
Processed audio for: Coming Over - Short Version B
Processed audio for: The 8 Oclock Story - Intro
Processed audio for: Modern Life Is Thin and Shallow
Processed audio for: Magnetic Storms - Short Version
Processed audio for: Preparing the Cannons
Processed audio for: Sharp Knives - Instrumental Version
Processed audio for: Rundown
Processed audio for: Be Quiet
Processed audio for: Little One - Short Version
Processed audio for: Begin Again - Short Version B
Processed audio for: Return - Short Version
Processed audio for: Energetic Loop
Processed audio for: The Most Important - Intro - No SFX
Processed audio for: Childhood Memory Ident
Processed audio for: No Land for a War Man - Short Version B
Processed audio for: Good Times
Processed audio for: Cinematic Fantasy Opener
Processed audio for: Orchestral Classic
Processed audio for: The Rain Part - Short Version
Processed audio for: Second Smile - Short Version A
Processed audio for: Lights - Alternative - Short Version
Processed audio for: Facebook - Short Version
Processed audio for: Fun to Wake Up
Processed audio for: Action Opening
Processed audio for: Fall - Short Version
Processed audio for: The Night of the Bowl
Processed audio for: Circus Clown - Short Version
Processed audio for: King of Mandol - Short Version B
Processed audio for: Star Dust - Short Version
Processed audio for: Others - Short Version B
Processed audio for: Voices - Short Version A
Processed audio for: SEVEN WONDERS 2
Processed audio for: Sneaky Pizzicato Logo
Processed audio for: Hard Rock Loop
Processed audio for: Extreme Power Lifter
Processed audio for: Mysterious Musical Ident 2
Processed audio for: Funk Band Intro 1
Processed audio for: Jester - Short Version
Processed audio for: Drive - Short Version
Processed audio for: Likes - Short Version B
Processed audio for: Trickster - Short Version
Processed audio for: Takes Me to the Lake - Short Version A
Processed audio for: Winter Lullaby - Short Version
Processed audio for: Astral Annihilation
Processed audio for: Forest Landspace
Processed audio for: Baritone Steel and Synth
Processed audio for: Happy in the Puddles - Short Version C
Processed audio for: A Furry Affair - Creative Cut - Alternative
Processed audio for: Mercury - Short Version
Processed audio for: The Oldest Man
Processed audio for: Promised - Short Version B
Processed audio for: I Remember - Short Version
Processed audio for: Infinite - Short Version
Processed audio for: Talk - Short Version
Processed audio for: Emotional Piano and Percussion 1
Processed audio for: Oriental Rock Opener 2
Processed audio for: Synth and Whistle
Processed audio for: Forever as a Melody - Short Version C
Processed audio for: Wild - Short Version
Processed audio for: Its That Feeling - Instrumental Version
Processed audio for: No Land for a War Man - Short Version A
Processed audio for: Oblivion Cult
Processed audio for: Chapter 2 - Short Version A
Processed audio for: Flow Free - Short Version
Processed audio for: Rancid Life - Short Version C
Processed audio for: Mandolin Guitars
Processed audio for: Dreaming - Short Version
Processed audio for: The Truth Is Close
Processed audio for: Emotional String Section Intro
Processed audio for: Cyber Warfare
Processed audio for: The Valley Man - Short Version A
Processed audio for: Dobro Band 2
Processed audio for: Northern Saints - Short Version A
Processed audio for: Event Ceremony Logo
Processed audio for: Positive Persistent Pluck Sequence 2
Processed audio for: Melancholic Sonata
Processed audio for: Call from the Hills - Short Version B
Processed audio for: Space Race - Short Version
Processed audio for: Otherworldly Tales Logo
Processed audio for: The Valley Man - Short Version B
Processed audio for: Warm Jamaica
Processed audio for: Freaky Boy
Processed audio for: Wonders of the Universe
Processed audio for: Fortitude - Short Version
Processed audio for: Counter
Processed audio for: Day One - Short Version A
Processed audio for: Shaal Region - Short Version
Processed audio for: Take Off - Short Version B
Processed audio for: We Will Get There - Short Version A
Processed audio for: Promised Land - Short Version B
Processed audio for: New World - Short Version B
Processed audio for: Variations on Ah vous dirai-je Maman - Var 3
Processed audio for: Energetic Funky Intro
Processed audio for: Greatest Epic Opener
Processed audio for: Happy Halloween 4
Processed audio for: Minor Ragtime Loop
Processed audio for: Sad Piano
Processed audio for: The Happy Intro
Processed audio for: For Kids
Processed audio for: Sad Cinematic Background Loop
Processed audio for: Inspiration
Processed audio for: Childrens Loop
Processed audio for: Power Up
Processed audio for: Creeping Prank
Processed audio for: Horror Trailer
Processed audio for: Convicted
Processed audio for: Happy Snowflake
Processed audio for: Upbeat Jazz Intro
Processed audio for: Documentary Background Loop
Processed audio for: Circus Game
Processed audio for: Deck The Halls Intro Opening
Processed audio for: Learn Grow
Processed audio for: Spring Acoustic Guitar
Processed audio for: Summer Opener Podcast Intro
Processed audio for: Ready Go!
Processed audio for: A Dark War Horn
Processed audio for: Soft Piano Intro Logo
Processed audio for: Wrongs
Processed audio for: Welcome Dream Orchestral Logo Intro
Processed audio for: Intense Trailer Ident
Processed audio for: Personal Hero Intro Trailer Opener
Processed audio for: For An Opener
Processed audio for: Cinematic Epic Trailer Intro
Processed audio for: Saxophone Made of Diamonds
Processed audio for: Kids Game
Processed audio for: Happy Ukulele Whistle Pop
Processed audio for: Happy Clap
Processed audio for: Cartoon Capers
Processed audio for: Fashion House Loop
Processed audio for: Audio Logo 029
Processed audio for: Minimal Technology Trailer
Processed audio for: Upbeat Whimsical Orchestra
Processed audio for: Background Funk
Processed audio for: Heavy Metal Loop
Processed audio for: Peaceful Corporate Ambient Loop
Processed audio for: Electrix 2
Processed audio for: Health
Processed audio for: Italian Dance
Processed audio for: The Indie Folk Acoustic Guitar Loop
Processed audio for: Energy Dance Loop
Processed audio for: Bossa Nova Lounge Jazz
Processed audio for: Modern Club Party
Processed audio for: Hard Rock Intro
Processed audio for: Comedy Music
Processed audio for: Little Ragtime
Processed audio for: Wild West Slow Dobro Guitar
Processed audio for: Black Magic Drama Tension
Processed audio for: Short Old England
Processed audio for: Into the Edge
Processed audio for: Disco Guitar Groove
Processed audio for: Energetic Rock Intro
Processed audio for: Children
Processed audio for: Vibes Of Summer Ukulele Happy
Processed audio for: Debussy Clair de Lune Slow Piano Intro
Processed audio for: Soft Ambient Dark Piano
Processed audio for: Ethnic Quena Flute
Processed audio for: Elegant Piano Valentines Podcast Intro
Processed audio for: Debussy Clair de Lune Piano and Flute Intro
Processed audio for: Acoustic Guitar Romantic Bright
Processed audio for: For Positive Logo
Processed audio for: Happy Logo Ident
Processed audio for: Energy Punk Rock Logo
Processed audio for: The Battle Begins
Processed audio for: Happy and Upbeat Intro Logo
Processed audio for: Attack of the Elfmen
Processed audio for: Corporate Loop Presentation
Processed audio for: Dynamic Promo
Processed audio for: Sports Theme
Processed audio for: Funky TV Show Food
Processed audio for: Moody Piano Intro Logo
Processed audio for: China Love Reveal Ident
Processed audio for: Ambient Soundscape Background Loop
Processed audio for: School Loop
Processed audio for: Inspirational Music Loop
Processed audio for: Blues Fingerpicking Guitar Loop
Processed audio for: Chillout Loop
Processed audio for: Sad Background Music Loop
Processed audio for: The Sadness Music
Processed audio for: Fragile Piano Ident
Processed audio for: The Sadness Piano Music
Processed audio for: Breaking News Opener
Processed audio for: Psy Trance Progressive
Processed audio for: Tango
Processed audio for: A Halloween
Processed audio for: Magical Fantasy Tale
Processed audio for: Fresh Catchy Pop Rock Anthem
Processed audio for: Ukulele Whistle (Loop)
Processed audio for: Orchestral News Intro
Processed audio for: Upbeat Happy Fun Logo
Processed audio for: Happy Birthday In Paris
Processed audio for: Funny Game Loop
Processed audio for: Classic Waltz Ident

In [4]:
import lancedb
db = lancedb.connect("./.lancedb_2")
table_audio = db.open_table("music_audio")
audio_embedding_df = table_audio.to_pandas()

audio_embedding_df

,song_name,song_path,audio_vector
0,My Rhapsody Sounds - Short Version A,music/Assaf Ayalon - My Rhapsody Sounds - Shor...,"[-0.029478367, 0.009709472, 0.05185532, 0.0254..."
1,Laid Back - Short Version A,music/The Mind Sweepers - Laid Back - Short Ve...,"[-0.033787563, 0.040226605, 0.004442984, 0.081..."
2,Far Taj,music/ZISO - Far Taj.mp3,"[-0.018721217, 0.035051364, 0.05141652, 0.0356..."
3,The Stones - Short Version,music/Wild Tulip - The Stones - Short Version.mp3,"[-0.008583562, 0.020294761, 0.0050604204, 0.03..."
4,Fixed - Short Version B,music/Swirling Ship - Fixed - Short Version B.mp3,"[0.0031058518, 0.020443501, 0.0060475464, -0.0..."
...,...,...,...
195,Orchestral News Intro,music/Tomasz_Redman - Orchestral News Intro.mp3,"[0.010141604, -0.017981885, 0.014272054, -0.03..."
196,Upbeat Happy Fun Logo,music/puremusic - Upbeat Happy Fun Logo.mp3,"[-0.031311695, -0.03104818, 0.022266045, 0.022..."
197,Happy Birthday In Paris,music/Music-Ideas - Happy Birthday In Paris.mp3,"[-0.049790498, -0.03626891, 0.059174698, -0.00..."
198,Funny Game Loop,music/honey_lemon - Funny Game Loop.wav,"[-0.045391183, -0.033096816, 0.025908915, -0.0..."
199,Classic Waltz Ident,music/_Blacksmith_ - Classic Waltz Ident.wav,"[0.013799119, 0.002807952, -0.0022102671, -0.0..."

In [5]:
table_text = db.open_table("music_text")
text_embedding_df = table_text.to_pandas()

text_embedding_df

,source,song_name,artist,mood,video_theme,genre,instrument,other_tags,bpm,lmm_description,combined_info,text_vector
0,Artlist,My Rhapsody Sounds - Short Version A,Assaf Ayalon,"Uplifting, Happy, Carefree, Love, Playful","Business, Food, Education, Lifestyle, Urban","Cinematic, Acoustic, Pop, Folk, Children, Corp...","Acoustic Guitar, Keys",,145.0,A positive and uplifting acoustic folk track w...,"Moods: Uplifting, Happy, Carefree, Love, Playf...","[0.00016941165, -0.011131651, -0.004014101, -0..."
1,Artlist,Laid Back - Short Version A,The Mind Sweepers,"Powerful, Serious, Angry","Road Trip, Sport & Fitness, Fashion, Industry",Rock,"Electric, Guitar, Acoustic Drums",,78.0,This is a powerful and energetic rock music tr...,"Moods: Powerful, Serious, Angry. Video Themes:...","[-0.0041819224, -0.01964485, -0.021090291, -0...."
2,Artlist,Far Taj,ZISO,"Uplifting, Powerful, Carefree, Groovy","Travel, Shorts","World, Electronic, Hip Hop","Ethnic, Electronic Drums, Bass",,96.0,A traditional Indian Bhangra track with modern...,"Moods: Uplifting, Powerful, Carefree, Groovy. ...","[-0.011723319, -0.008885955, 0.0040757894, -0...."
3,Artlist,The Stones - Short Version,Wild Tulip,"Love, Serious, Dramatic, Sad, Hopeful","Time-Lapse, Documentary, Road Trip, Medical, L...",Cinematic,Piano,,69.0,This piece is a solo piano instrumental with a...,"Moods: Love, Serious, Dramatic, Sad, Hopeful. ...","[0.0012076573, -0.0034555339, -0.0020917628, -..."
4,Artlist,Fixed - Short Version B,Swirling Ship,"Serious, Dramatic, Scary, Dark","Time-Lapse, Drone Shots, Nature, Slow Motion","Ambient, Country, Cinematic","Electric Guitar, Synth, Electronic Drums, Pads",,121.0,"The music is mysterious and dramatic, featurin...","Moods: Serious, Dramatic, Scary, Dark. Video T...","[-0.0021377725, -0.012590199, -0.013713269, -0..."
...,...,...,...,...,...,...,...,...,...,...,...,...
195,envato,Orchestral News Intro,Tomasz_Redman,"energetic, epic, powerful, solemn, uplifting","announcement, broadcast news, broadcasting, bu...",corporate,strings,global,125.0,This is a dynamic and uplifting music track th...,"Moods: energetic, epic, powerful, solemn, upli...","[-0.006809455, -0.016746698, -0.016968248, -0...."
196,envato,Upbeat Happy Fun Logo,puremusic,"bouncy, bright, catchy, cheerful, energetic, f...","commercial, happy logo, intro, kids, logo, sum...","acoustic, children","claps, ukulele","melody, youth",NaN,"A positive, upbeat, cheerful, and happy acoust...","Moods: bouncy, bright, catchy, cheerful, energ...","[0.002132031, -0.005020746, -0.0029374287, -0...."
197,envato,Happy Birthday In Paris,Music-Ideas,"cheerful, funny, happy, lively, playful, upbeat","ads, advertising, birthday, broadway, casino, ...","bigband, jazz, retro","accordion, piano, trumpets","france, french, paris",120.0,A fun and lively Latin track featuring a varie...,"Moods: cheerful, funny, happy, lively, playful...","[-0.012678004, -0.011919039, -0.00089095806, -..."
198,envato,Funny Game Loop,honey_lemon,"comical, fun, funny, laugh, smile, soft","cartoon, comedy, comic, kids, short, summer, tv","acoustic, children, folk, jazz",bells,loop,170.0,"A casual, jazzy, swing music with vibraphone, ...","Moods: comical, fun, funny, laugh, smile, soft...","[-0.012116052, -0.01674075, 0.010771282, -0.02..."
199,envato,Classic Waltz Ident,_Blacksmith_,"beautiful, calm, dramatic, dreamy, elegant, em...","commercial, film, wedding",cinematic,"piano, strings",,NaN,"A beautiful, passionate, romantic and elegant ...","Moods: beautiful, calm, dramatic, dreamy, eleg...","[-0.015361226, -0.01928933, -0.006900195, -0.0..."

In [7]:
text_embedding_df['combined_info']

0      Moods: Uplifting, Happy, Carefree, Love, Playf...
1      Moods: Powerful, Serious, Angry. Video Themes:...
2      Moods: Uplifting, Powerful, Carefree, Groovy. ...
3      Moods: Love, Serious, Dramatic, Sad, Hopeful. ...
4      Moods: Serious, Dramatic, Scary, Dark. Video T...
                             ...
195    Moods: energetic, epic, powerful, solemn, upli...
196    Moods: bouncy, bright, catchy, cheerful, energ...
197    Moods: cheerful, funny, happy, lively, playful...
198    Moods: comical, fun, funny, laugh, smile, soft...
199    Moods: beautiful, calm, dramatic, dreamy, eleg...
Name: combined_info, Length: 200, dtype: object